"""Restores a reproducible build path for /hun/, which had none: hun_page()/
hun_pool() are referenced by routes.py's docstring and a comment in
hunpayont.py but don't exist anywhere in this repo. The live docs/hun/
was generated by some one-off invocation of hunpayont.body() that's since
been lost; build_static.py just treats "hun" as UNMANAGED and preserves
whatever's already on disk.

Rather than reverse-engineer how POOL/stats were originally assembled, this
script reuses a snapshot of the numbers already baked into the currently-
published page (data/hun_pool_snapshot.json — the POOL dict, extracted
verbatim from the live <script> block; STATS below, read off the essay
prose: "13,020 priced listings", "404 hun payont for sale", "median ... is
฿130"), so regeneration is byte-for-byte equivalent to what's live before
any new-mode changes land on top.

Run manually, on demand, before publish_site.sh — deliberately NOT wired
into build_static.py's PAGE_SPECS/UNMANAGED handling, so the core build
pipeline for every other page is untouched.

Usage: .venv/bin/python3 build_hun.py [--out DOCS_DIR]
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

os.environ.setdefault("SITE_URL", "https://wichaa.net")

import build_static
import hunpayont
import wiki

HERE = Path(__file__).parent
DEFAULT_OUT = (
    HERE.parent / "nanobotco-lanna" / "docs" / "hun"
)

STATS = {"listings": 13020, "hun_listings": 404, "median": 130}

TITLE = "หุ่นพยนต์ · Hun Payont — wichaa"


def load_pool() -> dict:
    return json.loads((HERE / "data" / "hun_pool_snapshot.json").read_text(encoding="utf-8"))


def build(out_dir: Path) -> None:
    pool = load_pool()

    full_html = build_static.inject(wiki.page(
        TITLE,
        hunpayont.CSS,
        hunpayont.body(pool, STATS, wiki.NAV),
        description=hunpayont.DESCRIPTION,
        og_image="/hun/card.png",
        og_url="/hun/",
    ), "/")
    embed_html = build_static.inject(wiki.page(
        TITLE,
        hunpayont.CSS + hunpayont.EMBED_CSS,
        hunpayont.body(pool, STATS, "", embed=True),
        description=hunpayont.DESCRIPTION,
        og_image="/hun/card.png",
        og_url="/hun/embed/",
    ), "/")

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "index.html").write_text(full_html, encoding="utf-8")
    embed_dir = out_dir / "embed"
    embed_dir.mkdir(parents=True, exist_ok=True)
    (embed_dir / "index.html").write_text(embed_html, encoding="utf-8")
    print(f"wrote {out_dir / 'index.html'} ({len(full_html)} bytes)")
    print(f"wrote {embed_dir / 'index.html'} ({len(embed_html)} bytes)")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()
    build(args.out)
